---
- name: Portable, ephemeral, minimal development box.
  hosts: all
  sudo: true

  tasks:

    - apt: pkg=aptitude state=present

    - apt: upgrade=safe

    - name: Install base packages
      apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
      with_items:
          - git
          - subversion
          - mercurial
          - vim
          - rdesktop
          - openvpn
          - python-dev
          - gimp
          - sqlite
          - postgresql
          - libpq-dev
          - imagemagick
          - cifs-utils
          - xorg
          - zsh
          - encfs
          - chromium-browser
          - lightdm
          - unity-greeter

    - name: Virtualbox guest additions
      apt: pkg={{item}} state=present
      with_items:
          - virtualbox-guest-dkms
          - virtualbox-guest-x11
          - virtualbox-guest-utils

    - name: Add repo for latest version of i3 window manager
      apt_repository: repo='deb http://debian.sur5r.net/i3/ trusty universe' state=present

    - name: Add PPA for latest version of tmux
      apt_repository: repo='ppa:pi-rho/dev'

    - apt: update_cache=yes

    - name: Install latest tmux
      apt: name=tmux-next

    - name: Create link so that tmux plugin manager will work
      file: src=/usr/bin/tmux-next dest=/usr/local/bin/tmux state=link

    - apt: name=sur5r-keyring force=yes
    - apt: update_cache=yes
    - apt: name=i3

    - name: Install Vundle
      git: repo=https://github.com/VundleVim/Vundle.vim.git
           dest=~/.vim/bundle/Vundle.vim
      sudo: yes
      sudo_user: vagrant

    - name: Install tmux plugin manager
      git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm
      sudo: yes
      sudo_user: vagrant

    - shell: echo "[Seat:*]\nuser-session=i3" > /etc/lightdm/lightdm.conf
      args:
        creates: /etc/lightdm/lightdm.conf

    - service: name=lightdm state=restarted
